require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe VariablesController do

  def mock_variable(stubs={})
    @mock_variable ||= mock_model(Variable, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all variables as @variables" do
      Variable.stub(:all) { [mock_variable] }
      get :index
      assigns(:variables).should eq([mock_variable])
    end
  end

  describe "GET show" do
    it "assigns the requested variable as @variable" do
      Variable.stub(:find).with("37") { mock_variable }
      get :show, :id => "37"
      assigns(:variable).should be(mock_variable)
    end
  end

  describe "GET new" do
    it "assigns a new variable as @variable" do
      Variable.stub(:new) { mock_variable }
      get :new
      assigns(:variable).should be(mock_variable)
    end
  end

  describe "GET edit" do
    it "assigns the requested variable as @variable" do
      Variable.stub(:find).with("37") { mock_variable }
      get :edit, :id => "37"
      assigns(:variable).should be(mock_variable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created variable as @variable" do
        Variable.stub(:new).with({'these' => 'params'}) { mock_variable(:save => true) }
        post :create, :variable => {'these' => 'params'}
        assigns(:variable).should be(mock_variable)
      end

      it "redirects to the created variable" do
        Variable.stub(:new) { mock_variable(:save => true) }
        post :create, :variable => {}
        response.should redirect_to(variable_url(mock_variable))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved variable as @variable" do
        Variable.stub(:new).with({'these' => 'params'}) { mock_variable(:save => false) }
        post :create, :variable => {'these' => 'params'}
        assigns(:variable).should be(mock_variable)
      end

      it "re-renders the 'new' template" do
        Variable.stub(:new) { mock_variable(:save => false) }
        post :create, :variable => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested variable" do
        Variable.stub(:find).with("37") { mock_variable }
        mock_variable.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :variable => {'these' => 'params'}
      end

      it "assigns the requested variable as @variable" do
        Variable.stub(:find) { mock_variable(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:variable).should be(mock_variable)
      end

      it "redirects to the variable" do
        Variable.stub(:find) { mock_variable(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(variable_url(mock_variable))
      end
    end

    describe "with invalid params" do
      it "assigns the variable as @variable" do
        Variable.stub(:find) { mock_variable(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:variable).should be(mock_variable)
      end

      it "re-renders the 'edit' template" do
        Variable.stub(:find) { mock_variable(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested variable" do
      Variable.stub(:find).with("37") { mock_variable }
      mock_variable.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the variables list" do
      Variable.stub(:find) { mock_variable }
      delete :destroy, :id => "1"
      response.should redirect_to(variables_url)
    end
  end

end
